# Generated by Django 5.0.9 on 2025-12-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('contenu', models.TextField(blank=True, verbose_name='Contenu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/', verbose_name='Image principale')),
                ('video', models.FileField(blank=True, null=True, upload_to='articles/videos/', verbose_name='Vidéo')),
                ('audio', models.FileField(blank=True, null=True, upload_to='articles/audios/', verbose_name='Audio')),
                ('auteur', models.CharField(blank=True, max_length=100, verbose_name='Auteur')),
                ('categorie', models.CharField(blank=True, choices=[('news', 'Actualités'), ('tutorial', 'Tutoriel'), ('review', 'Revue'), ('other', 'Autre')], max_length=50, verbose_name='Catégorie')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('est_en_vedette', models.BooleanField(default=False, verbose_name='En vedette')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='EquipeGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_section', models.CharField(default='Notre Équipe', max_length=200)),
                ('description_section', models.TextField(default='Découvrez notre équipe passionnée et dévouée qui travaille chaque jour pour vous offrir la meilleure expérience.')),
                ('afficher_photos', models.BooleanField(default=True)),
                ('afficher_reseaux', models.BooleanField(default=True)),
                ('nombre_par_ligne', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (6, '6')], default=4)),
            ],
            options={
                'verbose_name': 'Configuration équipe',
                'verbose_name_plural': 'Configuration équipe',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('fichier', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('tags', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=200, verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('tcom', 'Technico-Commercial'), ('infor', 'Responsable Informatique'), ('Maket', 'Responsable Maketin'), ('admin', 'Administrateur'), ('other', 'Autre')], default='dev', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('photo_profil', models.ImageField(blank=True, default='equipe/photos/default-avatar.png', upload_to='equipe/photos/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Membre d'équipe",
                'verbose_name_plural': "Membres d'équipe",
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
    ]
